---
title: "hw2"
format: html
editor: visual
---

## load packages

```{r}
#| label: download
#| echo: true
#| warning: false
library(dataRetrieval)
library(tidyverse)
library(here)
```

# download water temperature data from the Willametter River

```{r}
#| label: download
#| echo: true
#| warning: false
siteNumbers <- c("14211720", "14211010", "14166000")
parameterCd <- "00010"  # water temperature
startDate <- "2010-01-01"
endDate <- "2023-12-31"

temp_data <- readNWISdv(siteNumbers, parameterCd, startDate, endDate)
```

clean the data

```{r}
#| label: clean
#| echo: true
# rename columns for clarity
colnames(temp_data) <- c("agency_cd", "site_no", "Date", "temp_C")
# extract some date info for use later
temp_data$month = month(temp_data$Date, label=TRUE)
temp_data$year = year(temp_data$Date)
```

plot the data

```{r}
#| label: plot
#| echo: true
# check by plotting
ggplot(temp_data, aes(x=Date, y=temp_C, color=site_no)) +
  geom_line() +
  labs(title="Stream Temperature at Willamette River Sites",
       x="Date", y="Temperature (°C)", color="Site Number") +
  theme_minimal()
```

store the data

```{r}
write.csv(temp_data, here("river_temp_data.csv"))
```

```{r}
#| label: summary-stats
#| echo: true

data <- read.csv(here("river_temp_data.csv"))
  
summary <- data|>
  select(agency_cd, site_no, temp_C, Date, month, year)|>
  group_by(site_no)|>
  summarise(mean_temp_c=mean(temp_C), max_temp_c=max(temp_C), min_temp_c=min(temp_C))

print(summary)
```





